;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Burst.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Burst.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="Nexus.Abilities.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Nexus.Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Nexus.Cooldown.Equip",DevComment="")
+GameplayTagList=(Tag="Nexus.Data.Damage",DevComment="")
+GameplayTagList=(Tag="Nexus.Data.Heal",DevComment="")
+GameplayTagList=(Tag="Nexus.Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Nexus.Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Nexus.Event.ActivateAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Nexus.Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Nexus.Weapons.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Nexus.Weapons.Ranged.Staff",DevComment="")

